// @ts-nocheck
import { default as __fd_glob_62 } from "../content/docs/customers/meta.json?collection=docs"
import { default as __fd_glob_61 } from "../content/docs/introduction/meta.json?collection=docs"
import { default as __fd_glob_60 } from "../content/docs/supplier/meta.json?collection=docs"
import { default as __fd_glob_59 } from "../content/docs/settings/meta.json?collection=docs"
import { default as __fd_glob_58 } from "../content/docs/sales/meta.json?collection=docs"
import { default as __fd_glob_57 } from "../content/docs/reports/meta.json?collection=docs"
import { default as __fd_glob_56 } from "../content/docs/purchases/meta.json?collection=docs"
import { default as __fd_glob_55 } from "../content/docs/inventory/meta.json?collection=docs"
import { default as __fd_glob_54 } from "../content/docs/clinics/meta.json?collection=docs"
import { default as __fd_glob_53 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_52 from "../content/docs/supplier/supplier-trash.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/supplier/supplier-profile.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/supplier/supplier-list.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/supplier/supplier-ledger.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/supplier/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/supplier/add-supplier.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/settings/user-management.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/settings/subscriptions.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/settings/referrals.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/settings/notifications.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/settings/modules.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/settings/invoice-counter.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/settings/integrations.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/settings/index.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/settings/data-management.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/settings/bill-templates.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/settings/accounting-settings.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/settings/account-info.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/sales/scan-and-ocr.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/sales/sale-list.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/sales/returned-sales.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/sales/re-orders.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/sales/index.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/sales/drafts.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/sales/add-sale.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/sales/add-credit-note.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/reports/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/inventory/trash.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/inventory/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/inventory/drug-list.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/inventory/create-debit-note.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/inventory/catalog-share.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/inventory/billing-notes.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/purchases/index.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/purchases/create-purchase.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/introduction/installation.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/introduction/index.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/introduction/getting-started.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/customers/store-request.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/customers/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/customers/customer-trash.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/customers/customer-profile.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/customers/customer-list.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/customers/customer-ledger.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/customers/billing-notes.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/customers/add-customer.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/clinics/schedules.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/clinics/prescriptions.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/clinics/pending-bookings.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/clinics/index.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/clinics/doctors.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/clinics/appointments.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/how-to-write.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_53, "clinics/meta.json": __fd_glob_54, "inventory/meta.json": __fd_glob_55, "purchases/meta.json": __fd_glob_56, "reports/meta.json": __fd_glob_57, "sales/meta.json": __fd_glob_58, "settings/meta.json": __fd_glob_59, "supplier/meta.json": __fd_glob_60, "introduction/meta.json": __fd_glob_61, "customers/meta.json": __fd_glob_62, }, {"how-to-write.mdx": __fd_glob_0, "clinics/appointments.mdx": __fd_glob_1, "clinics/doctors.mdx": __fd_glob_2, "clinics/index.mdx": __fd_glob_3, "clinics/pending-bookings.mdx": __fd_glob_4, "clinics/prescriptions.mdx": __fd_glob_5, "clinics/schedules.mdx": __fd_glob_6, "customers/add-customer.mdx": __fd_glob_7, "customers/billing-notes.mdx": __fd_glob_8, "customers/customer-ledger.mdx": __fd_glob_9, "customers/customer-list.mdx": __fd_glob_10, "customers/customer-profile.mdx": __fd_glob_11, "customers/customer-trash.mdx": __fd_glob_12, "customers/index.mdx": __fd_glob_13, "customers/store-request.mdx": __fd_glob_14, "introduction/getting-started.mdx": __fd_glob_15, "introduction/index.mdx": __fd_glob_16, "introduction/installation.mdx": __fd_glob_17, "purchases/create-purchase.mdx": __fd_glob_18, "purchases/index.mdx": __fd_glob_19, "inventory/billing-notes.mdx": __fd_glob_20, "inventory/catalog-share.mdx": __fd_glob_21, "inventory/create-debit-note.mdx": __fd_glob_22, "inventory/drug-list.mdx": __fd_glob_23, "inventory/index.mdx": __fd_glob_24, "inventory/trash.mdx": __fd_glob_25, "reports/index.mdx": __fd_glob_26, "sales/add-credit-note.mdx": __fd_glob_27, "sales/add-sale.mdx": __fd_glob_28, "sales/drafts.mdx": __fd_glob_29, "sales/index.mdx": __fd_glob_30, "sales/re-orders.mdx": __fd_glob_31, "sales/returned-sales.mdx": __fd_glob_32, "sales/sale-list.mdx": __fd_glob_33, "sales/scan-and-ocr.mdx": __fd_glob_34, "settings/account-info.mdx": __fd_glob_35, "settings/accounting-settings.mdx": __fd_glob_36, "settings/bill-templates.mdx": __fd_glob_37, "settings/data-management.mdx": __fd_glob_38, "settings/index.mdx": __fd_glob_39, "settings/integrations.mdx": __fd_glob_40, "settings/invoice-counter.mdx": __fd_glob_41, "settings/modules.mdx": __fd_glob_42, "settings/notifications.mdx": __fd_glob_43, "settings/referrals.mdx": __fd_glob_44, "settings/subscriptions.mdx": __fd_glob_45, "settings/user-management.mdx": __fd_glob_46, "supplier/add-supplier.mdx": __fd_glob_47, "supplier/index.mdx": __fd_glob_48, "supplier/supplier-ledger.mdx": __fd_glob_49, "supplier/supplier-list.mdx": __fd_glob_50, "supplier/supplier-profile.mdx": __fd_glob_51, "supplier/supplier-trash.mdx": __fd_glob_52, });